### ISSUE TITLE
Full example

### ISSUE THREAD

**Issue by luisbatista** [povils/omnipay-paysera#3]
Hello,

Is possible to have a full example how this work?

I can set the gateway, but problems to:
- set Customer fields;
- get all available payment methods, from Paysera, to the amount;
- set the payment method;
- set the cancel, accept and callback url's;
- make the purchase call with all parameters.

(note: in Stack Overflow can't find anything about this implementation )

Best regards,
LB

**Comment by povils** [comment]
Hey,

This library has the same API as the others Omnipay libraries. So if you will have any questions in the future I would firstly suggest to look at the official Omnipay gateway repository, also you could check tests. Because tests are perhaps the best documentation! :)

So ok, back to the questions.

- **Customers fields**
  How Omnipay deals with that (which actually I dont like it) is quite odd. It provides Credit object. I'll show later how to use it.

- **Get all available payment methods**
Sorry but at this moment there is no implementation of this. Primarily because there was no need of this in making transaction. If you think it is critical, you could send PR or if I'll manage to find some time I might implement this by myself.

- **Example**

```php       /** @var Gateway $gateway */
        $gateway = Omnipay::create('Paysera');
        $gateway
            ->setProjectId('project_id')
            ->setPassword('password');

        $card = new CreditCard(); // You customer info (name, email, adress)
        $card
            ->setFirstName('name')
            ->setLastName('last-name')
            ->setEmail('email@mail.com');

        $gateway
            ->purchase(
                array(
                    'transactionId' => 'order_id',
                    'returnUrl' => 'http://return-url.com', // Accept url
                    'cancelUrl' => 'http://cancel-url.com', // Cancel url
                    'notifyUrl' => 'http://notify-url.com', // Callback url
                    'language' => 'LIT',
                    'currency' => 'EUR',
                    'amount' => 10.0,
                    'payment_method' => 'hanza', // Payment method
                    'card' => $card,
                )
            )
            ->send()
            ->redirect();` // Redirects to off-gateway
```

If it doesnt work or something else, dont hesitate to ask! :)

Regards,

Povilas

**Comment by luisbatista** [comment]
Hello and many thanks Povilas :)

Omnipay looks very optimized for credit card payments, I got this idea about this lib.

Paysera has, by country, in addition to the credit card, its own wallet and the local payment methods of the country.

I want to be the user to choose which payment method want to use, and that the information of the chosen method is inserted in the Paysera gateway, I don't want to ask for this information, I will leave the security on the Paysera side without having to do "in my side".

I wish to pass to the gateway the customer data, information about the order and the amount, he can even pre-select the payment method, but it will always be in the Paysera gateway that the payment data request will be done (credit card, wallet Paysera or local payment).

I saw this lib, supported by Paysera: https://bitbucket.org/paysera/libwebtopay

It has the **getPaymentMethodList** that allows you to return the list of countries and payment methods that are valid for the amount and currency that will be paid, excluding what can not be used. It's a good addon, I guess, you avoid having to choose something that can not be picked by the user.
It has a "demo shop" where you can test these features.

Best Regards,
LB

**Comment by povils** [comment]
Hey again,

I hope I will look at this in the near future. But I'm not sure what do you mean by saying "I wish to pass to the gateway the customer data, information about the order and the amount, he can even pre-select the payment method". Because as I understand this is all possible.

Regards,
Povilas

**Comment by luisbatista** [comment]
Good morning Povilas and thank you.

My phrase was to indicate what I'm trying to implement.
I will do some tests using this lib.

Best Regards,
LB
